In [1]:
#normalization using min-max scaling example
import numpy as np
data =np.array([1,2,3,4,5],dtype = float)
min_value = np.min(data)
max_value = np.max(data)
scaled_data = (data - min_value)/ (max_value - min_value)
scaled_data

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
#normalization using z-score normalization
data = np.array([5,6,7,8,9],dtype=float)
mean_val=np.mean(data)
std_val = np.std(data)
norm_data= (data - mean_val) / std_val
norm_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [4]:
#normalization by the L2 technique
data = np.array([1,2,3,4,5],dtype = float)
magnitude = np.linalg.norm(data)
norm_data = data/magnitude
print("Original data :",data)
print("Normalized data:",norm_data)

Original data : [1. 2. 3. 4. 5.]
Normalized data: [0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


In [7]:
#image normalization
image = np.array([
    [[10,20,30],[40,50,60],[70,80,90]],
    [[15,25,35],[45,55,65],[75,85,95]]
])
norm_image = image/255.0
#calculating the mean pixel intensity per channel and normalizing each channel to range[0,1]
mean_per_channel= np.mean(image,axis =(0,1))
print("Image shape:",image.shape)
print("Normalized Image:",norm_image)
print("Mean Per Channel:",mean_per_channel)

Image shape: (2, 3, 3)
Normalized Image: [[[0.03921569 0.07843137 0.11764706]
  [0.15686275 0.19607843 0.23529412]
  [0.2745098  0.31372549 0.35294118]]

 [[0.05882353 0.09803922 0.1372549 ]
  [0.17647059 0.21568627 0.25490196]
  [0.29411765 0.33333333 0.37254902]]]
Mean Per Channel: [42.5 52.5 62.5]


In [14]:
#computing using loops
#convert type to float
image = image.astype(np.float32)
#create a copy for looping
norm_loop= image.copy()
#for loop
for c in range(image.shape[2]):
    channel = image[:,:,c]
    mean = np.mean(channel)
    std = np.std(channel)
    norm_loop[:,:,c]=(channel - mean)/std
print("Original Image:\n",image)
print("Loop:\n",norm_loop)

Original Image:
 [[[10. 20. 30.]
  [40. 50. 60.]
  [70. 80. 90.]]

 [[15. 25. 35.]
  [45. 55. 65.]
  [75. 85. 95.]]]
Loop:
 [[[-1.31995    -1.31995    -1.31995   ]
  [-0.10153461 -0.10153461 -0.10153461]
  [ 1.1168808   1.1168808   1.1168808 ]]

 [[-1.1168808  -1.1168808  -1.1168808 ]
  [ 0.10153461  0.10153461  0.10153461]
  [ 1.31995     1.31995     1.31995   ]]]


In [13]:
#computing using broadcasting
mean = np.mean(image,axis=(0,1), keepdims=True)
std= np.std(image,axis=(0,1),keepdims = True)
broad_data = (image-mean)/std
print("Broadcasted Normalization:\n",broad_data)
               

Broadcasted Normalization:
 [[[-1.31995    -1.31995    -1.31995   ]
  [-0.10153461 -0.10153461 -0.10153461]
  [ 1.1168808   1.1168808   1.1168808 ]]

 [[-1.1168808  -1.1168808  -1.1168808 ]
  [ 0.10153461  0.10153461  0.10153461]
  [ 1.31995     1.31995     1.31995   ]]]


In [22]:
#compare the speed between using loops and broadcsting   
# Measure loop version speed
%timeit for c in range(image.shape[2]): (image[:, :, c] - np.mean(image[:, :, c])) / np.std(image[:, :, c])

# Measure broadcasting version speed
%timeit (image - np.mean(image, axis=(0, 1), keepdims=True)) / np.std(image, axis=(0, 1), keepdims=True)


299 μs ± 62.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
100 μs ± 3.02 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
